version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_calendar
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    env_file:
      - ../.env

volumes:
  postgres_data:
    driver: local