"""29.07.2024_user_access_calendar

Revision ID: 1eb3ebda0dcc
Revises: f5685ce40d61
Create Date: 2024-07-29 14:41:47.986437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1eb3ebda0dcc'
down_revision: Union[str, None] = 'f5685ce40d61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_access',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('accessible_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['accessible_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('username', sa.String(length=50), nullable=True))
    op.drop_constraint('user_login_key', 'user', type_='unique')
    op.create_unique_constraint(None, 'user', ['username'])
    op.drop_column('user', 'login')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('login', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user', type_='unique')
    op.create_unique_constraint('user_login_key', 'user', ['login'])
    op.drop_column('user', 'username')
    op.drop_table('calendar_access')
    # ### end Alembic commands ###
