"""29.07.2024_final_user_access_calendar

Revision ID: 343b4f5539b4
Revises: 1eb3ebda0dcc
Create Date: 2024-07-29 14:52:44.235081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '343b4f5539b4'
down_revision: Union[str, None] = '1eb3ebda0dcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
